#!/usr/bin/env python3
"""Offline Gitleaks adapter and strict redacted-report renderer (stdlib only)."""
import json
import ntpath
import os
from pathlib import Path
import re
import shutil
import signal
import stat
import subprocess
import sys
import tempfile
import time

VERSION = "8.30.1"
MAX_BYTES = 8 * 1024 * 1024
# 範本附帶的 skill：只有引擎自己的這一個，它永遠是集合的第一個。實際同步的集合由每個
# source snapshot 自己的目錄決定（skills_in）；還沒有 skill 目錄的 source 使用這份清單。
SKILLS = ('dotfiles-sync',)
SKILL_LIMIT = 64
PROFILES = ('claude', 'codex', 'claude-codex')
PREFIX = '.chezmoitemplates/ai/'
SKILL_ROOT = PREFIX + 'shared/skills/'
# 每個 skill 自己的路徑：（前綴，後綴）。前三組是 source，接著是兩個部署目標，最後是 v1 的來源。
SKILL_SOURCES = ((SKILL_ROOT, '/SKILL.md'), ('dot_claude/skills/', '/SKILL.md.tmpl'),
                 ('dot_agents/skills/', '/SKILL.md.tmpl'))
SKILL_TARGETS = (('.claude/skills/', '/SKILL.md'), ('.agents/skills/', '/SKILL.md'))
SKILL_LEGACY = (('dot_claude/skills/', '/SKILL.md'),)
SCRIPTS = ('sync.sh', 'scan-secrets.py', 'sync-write.py', 'sync-migrate.py', 'gitleaks-rules.json')
BANNER = b'<!-- Generated by chezmoi. Edit .chezmoitemplates/ai/ in the source. -->\n'

# ---- 平台層（#33）：所有依賴作業系統的判斷集中在這裡。POSIX 分支逐字保留原本的行為；Windows 分支
# 只做明顯正確的部分；擁有者與權限以 ACL 判定（#38），重導向含 reparse point（#39）。
WINDOWS = sys.platform == 'win32'


def temporary_root():
    """引擎所有暫存狀態的固定根目錄：POSIX 是 /tmp；Windows 是使用者的暫存目錄（%TEMP%）。"""
    return Path(tempfile.gettempdir()) if WINDOWS else Path('/tmp')


def is_redirected(path):
    """路徑本身是不是重導向：POSIX 是 symlink；Windows 是任何 reparse point（symlink、junction、
    mount point 等，#39）。路徑不存在回 False，與 is_symlink 相同。"""
    if not WINDOWS:
        return Path(path).is_symlink()
    try:
        info = os.lstat(path)
    except (FileNotFoundError, NotADirectoryError):
        return False
    return bool(info.st_file_attributes & stat.FILE_ATTRIBUTE_REPARSE_POINT)


def scratch_conflict(src, dst, scratch):
    """選定的根目錄不得等於或包含引擎的暫存根。POSIX 看 source 與 destination（例如 HOME=/tmp）。
    Windows：%TEMP% 必然在使用者目錄下，改看 source 與每個部署區；暫存根底下的 source（像 POSIX 的
    /tmp/src）照樣允許，暫存目錄本身由 make_private 保護。"""
    roots = (src, *(dst / region for region in TARGET_REGIONS)) if WINDOWS else (src, dst)
    return any(root == scratch or root in scratch.parents for root in roots)


def absolute_path(value):
    """參數檔裡的路徑格式：POSIX 要求 / 開頭；Windows 要求含磁碟機的絕對路徑。"""
    if WINDOWS:
        return ntpath.isabs(value) and bool(ntpath.splitdrive(value)[0])
    return value.startswith('/')


# Windows 的 ACL（#38）：POSIX 600／700 的等價是「owner 是目前使用者，而且 DACL 只允許使用者、SYSTEM、
# Administrators（以及代表擁有者的 OWNER RIGHTS）」。讀取用 ctypes 取 SDDL，判定是純函式；設定用 icacls，
# 以 SID 寫法、只看 exit code，不解析在地化的輸出。
ACL_ALIASES = {'SY': 'S-1-5-18', 'BA': 'S-1-5-32-544', 'OW': 'S-1-3-4'}
ACL_TRUSTED = ('S-1-5-18', 'S-1-5-32-544', 'S-1-3-4')
# SDDL 的權限代碼（檔案與通用權限；registry 的 KA/KR/KW/KX 只為了解析不失敗）
ACL_RIGHTS = dict(GA=0x10000000, GR=0x80000000, GW=0x40000000, GX=0x20000000, RC=0x20000, SD=0x10000,
                  WD=0x40000, WO=0x80000, FA=0x1F01FF, FR=0x120089, FW=0x120116, FX=0x1200A0,
                  KA=0xF003F, KR=0x20019, KW=0x20006, KX=0x20019,
                  CC=0x1, DC=0x2, LC=0x4, SW=0x8, RP=0x10, WP=0x20, DT=0x40, LO=0x80, CR=0x100)
# 寫入類權限：FILE_WRITE_DATA、FILE_APPEND_DATA、FILE_WRITE_EA、FILE_WRITE_ATTRIBUTES、DELETE、
# WRITE_DAC、WRITE_OWNER、GENERIC_WRITE、GENERIC_ALL
ACL_WRITE = 0x2 | 0x4 | 0x10 | 0x100 | 0x10000 | 0x40000 | 0x80000 | 0x40000000 | 0x10000000
ACL_ALLOW = ('A', 'XA')


def parse_sddl(text):
    """SDDL 字串 → (owner SID, [(ACE 類型, 旗標, 權限遮罩, SID)])。只看 O: 與 D: 區段；別名翻成 SID，
    未知別名原樣保留（之後一律視為其他主體）。格式不對就 ValueError。"""
    owner = re.search(r'O:(S-[0-9-]+|[A-Z]{2})', text)
    dacl = re.search(r'D:[A-Z]*((?:\([^)]*\))*)', text)
    if not owner or not dacl:
        raise ValueError('sddl')
    aces = []
    for ace in re.findall(r'\(([^)]*)\)', dacl.group(1)):
        fields = ace.split(';')
        if len(fields) < 6:
            raise ValueError('sddl ace')
        rights = fields[2]
        if rights.startswith('0x'):
            mask = int(rights, 16)
        else:
            if len(rights) % 2 or any(rights[i:i + 2] not in ACL_RIGHTS for i in range(0, len(rights), 2)):
                raise ValueError('sddl rights')
            mask = 0
            for i in range(0, len(rights), 2):
                mask |= ACL_RIGHTS[rights[i:i + 2]]
        aces.append((fields[0], fields[1], mask, ACL_ALIASES.get(fields[5], fields[5])))
    return ACL_ALIASES.get(owner.group(1), owner.group(1)), aces


def domain_alias(sid, user):
    """SDDL 的網域相對別名：LA 是本機 Administrator 帳號（RID 500）、LG 是 Guest（501），只有展開成
    目前使用者網域下的 SID 才能和使用者比對（CI runner 就是以 Administrator 帳號執行）。"""
    domain = user.rsplit('-', 1)[0]
    return {'LA': domain + '-500', 'LG': domain + '-501'}.get(sid, sid)


def acl_private(descriptor, user, owner=None):
    """owner 是使用者，或是這個程序建立新物件時會指定的 owner（提升權限的 Administrator 建立的檔案由
    Administrators 群組擁有，例如 CI runner）；而且每個 allow ACE 的主體都是使用者、SYSTEM、Administrators
    或 OWNER RIGHTS。deny ACE 只會限制，不影響判定。"""
    actual, aces = descriptor
    return (domain_alias(actual, user) in (user, owner or user)
            and all(kind not in ACL_ALLOW or domain_alias(sid, user) in (user,) + ACL_TRUSTED
                    for kind, _, _, sid in aces))


def acl_foreign_writable(descriptor, user):
    """使用者、SYSTEM、Administrators、OWNER RIGHTS 以外的主體持有寫入類權限；POSIX 的 group/other 可寫。"""
    return any(kind in ACL_ALLOW and domain_alias(sid, user) not in (user,) + ACL_TRUSTED and mask & ACL_WRITE
               for kind, _, mask, sid in descriptor[1])


def windows_api():
    import ctypes
    import ctypes.wintypes as wt
    advapi32 = ctypes.WinDLL('advapi32', use_last_error=True)
    kernel32 = ctypes.WinDLL('kernel32', use_last_error=True)
    kernel32.GetCurrentProcess.restype = wt.HANDLE
    kernel32.LocalFree.argtypes = [wt.HLOCAL]
    kernel32.CloseHandle.argtypes = [wt.HANDLE]
    advapi32.OpenProcessToken.argtypes = [wt.HANDLE, wt.DWORD, ctypes.POINTER(wt.HANDLE)]
    advapi32.GetTokenInformation.argtypes = [wt.HANDLE, ctypes.c_int, ctypes.c_void_p, wt.DWORD, ctypes.POINTER(wt.DWORD)]
    advapi32.ConvertSidToStringSidW.argtypes = [ctypes.c_void_p, ctypes.POINTER(wt.LPWSTR)]
    advapi32.GetFileSecurityW.argtypes = [wt.LPCWSTR, wt.DWORD, ctypes.c_void_p, wt.DWORD, ctypes.POINTER(wt.DWORD)]
    advapi32.ConvertSecurityDescriptorToStringSecurityDescriptorW.argtypes = [
        ctypes.c_void_p, wt.DWORD, wt.DWORD, ctypes.POINTER(wt.LPWSTR), ctypes.POINTER(wt.ULONG)]
    return ctypes, wt, advapi32, kernel32


def security_descriptor(path):
    """以 ctypes 讀取檔案或目錄的 owner 與 DACL；只在 Windows 呼叫。失敗是 OSError。"""
    ctypes, wt, advapi32, kernel32 = windows_api()
    flags = 0x1 | 0x4  # OWNER_SECURITY_INFORMATION | DACL_SECURITY_INFORMATION
    needed = wt.DWORD(0)
    advapi32.GetFileSecurityW(str(path), flags, None, 0, ctypes.byref(needed))
    buffer = ctypes.create_string_buffer(needed.value)
    if not advapi32.GetFileSecurityW(str(path), flags, buffer, needed, ctypes.byref(needed)):
        raise ctypes.WinError(ctypes.get_last_error())
    text = wt.LPWSTR()
    if not advapi32.ConvertSecurityDescriptorToStringSecurityDescriptorW(buffer, 1, flags, ctypes.byref(text), None):
        raise ctypes.WinError(ctypes.get_last_error())
    try:
        return parse_sddl(text.value)
    finally:
        kernel32.LocalFree(text)


USER_SID = None
OWNER_SID = None


def token_sid(kind):
    """目前程序 token 的 SID：kind 1 是 TokenUser（使用者），4 是 TokenOwner（新物件的預設 owner）。"""
    ctypes, wt, advapi32, kernel32 = windows_api()
    token = wt.HANDLE()
    if not advapi32.OpenProcessToken(kernel32.GetCurrentProcess(), 0x8, ctypes.byref(token)):  # TOKEN_QUERY
        raise ctypes.WinError(ctypes.get_last_error())
    try:
        needed = wt.DWORD(0)
        advapi32.GetTokenInformation(token, kind, None, 0, ctypes.byref(needed))
        buffer = ctypes.create_string_buffer(needed.value)
        if not advapi32.GetTokenInformation(token, kind, buffer, needed, ctypes.byref(needed)):
            raise ctypes.WinError(ctypes.get_last_error())
        # TOKEN_USER 與 TOKEN_OWNER 的第一個欄位都是 PSID
        sid = ctypes.cast(buffer, ctypes.POINTER(ctypes.c_void_p))[0]
        text = wt.LPWSTR()
        if not advapi32.ConvertSidToStringSidW(sid, ctypes.byref(text)):
            raise ctypes.WinError(ctypes.get_last_error())
        try:
            return text.value
        finally:
            kernel32.LocalFree(text)
    finally:
        kernel32.CloseHandle(token)


def current_user_sid():
    """目前使用者的 SID；只在 Windows 呼叫，結果快取。"""
    global USER_SID
    if not USER_SID:
        USER_SID = token_sid(1)
    return USER_SID


def token_owner_sid():
    """這個程序建立新檔案時會指定的 owner SID：一般是使用者，提升權限時是 Administrators。"""
    global OWNER_SID
    if not OWNER_SID:
        OWNER_SID = token_sid(4)
    return OWNER_SID


def private_file(path, info):
    """擁有者是自己，而且 group／other 不可寫；Windows 看 owner 與 DACL。"""
    if WINDOWS:
        return acl_private(security_descriptor(path), current_user_sid(), token_owner_sid())
    return info.st_uid == os.getuid() and not info.st_mode & 0o022


def private_mode(path, mode):
    """只有擁有者能存取（plan 檔、manifest）；Windows 看 owner 與 DACL。"""
    if WINDOWS:
        return acl_private(security_descriptor(path), current_user_sid(), token_owner_sid())
    return mode & 0o077 == 0


def foreign_writable(path, info):
    """比標準 644／755 寬鬆：POSIX 是 group 或 other 可寫；Windows 是其他主體持有寫入類權限。"""
    if WINDOWS:
        return acl_foreign_writable(security_descriptor(path), current_user_sid())
    return bool(stat.S_IMODE(info.st_mode) & 0o022)


def private_grants(path):
    """icacls 的授權參數：使用者、SYSTEM、Administrators 各 Full；目錄加上讓子項繼承的旗標。"""
    inherit = '(OI)(CI)' if os.path.isdir(path) else ''
    return ['*%s:%sF' % (sid, inherit) for sid in (current_user_sid(),) + ACL_TRUSTED[:2]]


def private_hint(path):
    """使用者自己要把一個檔案或目錄設成私有時的指令（doctor 與文件用）。"""
    if WINDOWS:
        return 'icacls "%s" /inheritance:r /grant:r %s' % (path, ' '.join(private_grants(path)))
    return 'chmod %s %s' % ('700' if os.path.isdir(path) else '600', path)


def make_private(path):
    """引擎自己建立的私有檔案或目錄。POSIX 已由 mode 參數與 umask 077 決定，不做事；Windows 移除繼承、
    只授權使用者、SYSTEM、Administrators，然後讀回確認。"""
    if not WINDOWS:
        return
    # /reset 先丟掉明確的 ACE（例如使用者自己加的 Everyone），/inheritance:r 再移除繼承的，最後只授權三個主體
    for arguments in (['/reset'], ['/inheritance:r', '/grant:r', *private_grants(path)]):
        run = subprocess.run(['icacls', str(path), *arguments], stdin=subprocess.DEVNULL,
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=60)
        if run.returncode != 0:
            raise OSError('icacls failed: ' + str(path))
    descriptor = security_descriptor(path)
    if not acl_private(descriptor, current_user_sid(), token_owner_sid()):
        # 只含 SID 與權限遮罩，沒有檔案內容；CI 等看不到桌面的環境靠這行判斷原因
        raise OSError('private acl not applied: %s owner=%s aces=%s user=%s token_owner=%s'
                      % (path, descriptor[0], descriptor[1], current_user_sid(), token_owner_sid()))


def protect(path):
    """上線時把參數檔或 plan_dir 設成只有自己能存取：POSIX 用 chmod 600／700，Windows 用 ACL。"""
    if WINDOWS:
        make_private(path)
    else:
        os.chmod(path, 0o700 if os.path.isdir(path) else 0o600)


def private_directory_report(path):
    """doctor 的 plan_dir 檢查：(通過, 說明, 修正)。POSIX 要求正好 700。"""
    if WINDOWS:
        ok = acl_private(security_descriptor(path), current_user_sid(), token_owner_sid())
        return ok, ' acl private' if ok else ' acl open to other principals', '' if ok else private_hint(path)
    mode = stat.S_IMODE(os.stat(path).st_mode)
    return mode == 0o700, ' mode %o' % mode, '' if mode == 0o700 else 'chmod 700 ' + str(path)


def set_mode(fd, mode):
    """寫入時設定檔案模式。Windows 沒有 mode bits（os.fchmod 要 3.13 才有），私有檔案由 make_private 的
    ACL 處理，這裡不做事。"""
    if not WINDOWS:
        os.fchmod(fd, mode)


def open_directory(path):
    """取得目錄的檔案描述子供 fsync 用；Windows 沒有目錄 fsync，回傳 None。"""
    return None if WINDOWS else os.open(path, os.O_RDONLY | os.O_DIRECTORY)


def replace(source, target):
    """原子取代。Windows 上目標被其他程式短暫開著（防毒、正在讀取的 agent）會得到 PermissionError：
    有限次重試，仍失敗就照常拋出。"""
    if not WINDOWS:
        os.replace(source, target)
        return
    for attempt in range(5):
        try:
            os.replace(source, target)
            return
        except PermissionError:
            if attempt == 4:
                raise
            time.sleep(0.2 * (attempt + 1))


def child_environment(home, path=None):
    """子程序的最小環境：只有 PATH、HOME 與 C locale。Windows 的 git 與 chezmoi 還需要系統目錄、
    PATHEXT、暫存目錄與 COMSPEC；USERPROFILE 也指到隔離的 home，不讓它們讀到使用者的設定。"""
    env = {'PATH': os.defpath if path is None else path, 'HOME': str(home), 'LC_ALL': 'C'}
    if WINDOWS:
        for key in ('SystemRoot', 'SystemDrive', 'PATHEXT', 'TEMP', 'TMP', 'COMSPEC'):
            if os.environ.get(key):
                env[key] = os.environ[key]
        env['USERPROFILE'] = str(home)
    return env


def scanner_command(path):
    """scanner 以執行檔身分呼叫；Windows 沒有 shebang，交給目前的 Python 直譯器。"""
    return [sys.executable, str(path)] if WINDOWS else [str(path)]


def observed_mode(info, expected):
    """快照記錄的檔案模式。POSIX 是 stat 的 mode bits；Windows 沒有 mode bits，記錄預期值（source 檔是
    HEAD 的模式、target 是 mapping 的標準模式、其他 644）：執行位元由 git 承擔、寬鬆權限由 ACL 承擔。"""
    return expected if WINDOWS else stat.S_IMODE(info.st_mode)


def executable_bit(path, index_mode):
    """status 判斷工作目錄檔案的執行位元：POSIX 看檔案系統；Windows 以 index 為準（沒有 entry 就是 644）。"""
    if WINDOWS:
        return index_mode == '100755'
    return os.access(path, os.X_OK)


def target_executable(path):
    """部署的腳本要可執行；Windows 沒有執行位元，腳本經由 sh 與 python 執行，條件永遠成立。"""
    return True if WINDOWS else os.access(path, os.X_OK)


def target_mode(rel):
    """部署檔的標準模式：引擎腳本與相容入口 755，其餘 644；與 render 的規則相同。"""
    if rel.startswith('.config/ai-agent/bin/'):
        return 0o644 if rel.endswith('.json') else 0o755
    return 0o755 if rel == '.claude/skills/dotfiles-sync/sync.sh' else 0o644


def target_modes(paths):
    return {p: target_mode(p) for p in paths}


def umask_applies():
    """chezmoi 的 umask 設定只在有 mode bits 的平台有意義。"""
    return not WINDOWS


def config_refused(path, label, reason=''):
    """參數檔不被接受時的標籤；Windows 補上原因與把它設成私有的指令。"""
    if not WINDOWS:
        return label
    return label + ('; ' + reason if reason else '') + '; ' + private_hint(path)


def skill_names(names):
    """One closed, ordered set: validated names, the engine's own skill first, the rest sorted."""
    names = set(names) | {SKILLS[0]}
    if len(names) > SKILL_LIMIT or not all(re.fullmatch('[a-z0-9][a-z0-9-]{0,63}', n) for n in names):
        raise ValueError('skill name')
    return (SKILLS[0],) + tuple(sorted(names - {SKILLS[0]}))


def skill_of(path, kinds=SKILL_SOURCES + SKILL_TARGETS + SKILL_LEGACY):
    """Directory name of the skill a per-skill path belongs to, or None. The name is not validated."""
    for prefix, suffix in kinds:
        if path.startswith(prefix) and path.endswith(suffix):
            name = path[len(prefix):len(path) - len(suffix)]
            if name and '/' not in name:
                return name
    return None


def skills_in(paths, profile='claude-codex'):
    """Skill set of one source snapshot, from its own paths (a Git tree or a working tree listing).

    A skill is a directory with a SKILL.md under the shared skill root. Every other
    path there stays out of scope. A wrapper without its skill would break a real
    chezmoi render, so it is refused instead of ignored.
    """
    if profile not in PROFILES:
        raise ValueError('invalid profile')
    paths = set(paths)
    names = skill_names(filter(None, (skill_of(p, SKILL_SOURCES[:1]) for p in paths)))
    wrappers = [kind for kind, product in zip(SKILL_SOURCES[1:], ('claude', 'codex')) if product in profile]
    if any(skill_of(p, wrappers) not in names + (None,) for p in paths):
        raise ValueError('wrapper without skill')
    return names


def source_skills(source, profile='claude-codex'):
    """Skill set of the working tree. Lists three fixed source directories, never the destination."""
    root = Path(source)
    paths = []
    for prefix, suffix in SKILL_SOURCES:
        directory = root / prefix
        if any(is_redirected(part) for part in (directory, *directory.parents) if part != root and root in part.parents):
            raise ValueError('managed symlink')
        if not directory.is_dir():
            if prefix == SKILL_ROOT:
                return SKILLS
            continue
        entries = os.listdir(directory)
        if len(entries) > 4096:
            raise ValueError('skill directory')
        paths += [prefix + name + suffix for name in entries if os.path.lexists(str(directory / name) + suffix)]
    return skills_in(paths, profile)


def legacy_skills(source):
    """Skill set of a v1 source: every directory with a SKILL.md under dot_claude/skills."""
    root = Path(source)
    directory = root / 'dot_claude/skills'
    if any(is_redirected(part) for part in (directory, *directory.parents) if part != root and root in part.parents):
        raise ValueError('managed symlink')
    if not directory.is_dir():
        return skill_names(())
    entries = os.listdir(directory)
    if len(entries) > 4096:
        raise ValueError('skill directory')
    return skill_names(name for name in entries if os.path.lexists(directory / name / 'SKILL.md'))


def legacy_files(skills=SKILLS):
    return ('dot_claude/CLAUDE.md', 'dot_claude/settings.json', 'dot_claude/skills/dotfiles-sync/executable_sync.sh',
            '.chezmoiignore', '.gitignore', '.gitattributes') + tuple(
                'dot_claude/skills/' + s + '/SKILL.md' for s in skills)


def legacy_targets(skills=SKILLS):
    return ('.claude/CLAUDE.md', '.claude/settings.json', '.claude/skills/dotfiles-sync/sync.sh') + tuple(
        '.claude/skills/' + s + '/SKILL.md' for s in skills)


def mapping(profile, skills=SKILLS):
    if profile not in PROFILES:
        raise ValueError('invalid profile')
    products = ('claude', 'codex') if profile == 'claude-codex' else (profile,)
    sources = [PREFIX + 'shared/instructions.md']
    sources += [SKILL_ROOT + s + '/SKILL.md' for s in skills]
    sources += [PREFIX + 'shared/scripts/' + s for s in SCRIPTS]
    if 'claude' in products:
        sources += [PREFIX + 'shared/scripts/legacy-sync.sh']
    sources += [PREFIX + 'adapters/' + p + '.md' for p in products]
    targets = []
    for product in products:
        sources.append('dot_' + product + ('/CLAUDE.md.tmpl' if product == 'claude' else '/AGENTS.md.tmpl'))
        targets.append('.' + product + ('/CLAUDE.md' if product == 'claude' else '/AGENTS.md'))
        skill_home = 'claude' if product == 'claude' else 'agents'
        for skill in skills:
            sources.append('dot_' + skill_home + '/skills/' + skill + '/SKILL.md.tmpl')
            targets.append('.' + skill_home + '/skills/' + skill + '/SKILL.md')
    for name in SCRIPTS:
        sources.append('dot_config/ai-agent/bin/' + ('' if name.endswith('.json') else 'executable_') + name + '.tmpl')
        targets.append('.config/ai-agent/bin/' + name)
    if 'claude' in products:
        sources += ['dot_claude/skills/dotfiles-sync/executable_sync.sh.tmpl', 'dot_claude/settings.json']
        targets += ['.claude/skills/dotfiles-sync/sync.sh', '.claude/settings.json']
    sources += ['.chezmoiignore', '.gitignore', '.gitattributes']
    return tuple(sources), tuple(targets)


def wrapper(path):
    opening, closing = '{' * 2, '}' * 2
    def include(p, trim=True):
        name = p[len('.chezmoitemplates/'):]
        return (opening + ' template "' + name + '" . ' + ('-' if trim else '') + closing + '\n').encode()
    if path in ('dot_claude/CLAUDE.md.tmpl', 'dot_codex/AGENTS.md.tmpl'):
        product = 'claude' if path.startswith('dot_claude/') else 'codex'
        return BANNER + include(PREFIX + 'shared/instructions.md', False) + include(PREFIX + 'adapters/' + product + '.md')
    skill = skill_of(path, SKILL_SOURCES[1:])
    if skill:
        return include(SKILL_ROOT + skill_names([skill])[-1] + '/SKILL.md')
    if path == 'dot_claude/skills/dotfiles-sync/executable_sync.sh.tmpl':
        return include(PREFIX + 'shared/scripts/legacy-sync.sh')
    for script in SCRIPTS:
        if path == 'dot_config/ai-agent/bin/' + ('' if script.endswith('.json') else 'executable_') + script + '.tmpl':
            return include(PREFIX + 'shared/scripts/' + script)
    raise ValueError('unknown wrapper')


OPEN = b'{' * 2
LITERAL_OPEN = OPEN + b' "' + OPEN + b'" ' + b'}' * 2


def encode_shared(content):
    """Represent arbitrary literal UTF-8 text using only a static opener escape."""
    return content.replace(OPEN, LITERAL_OPEN)


def decode_shared(content):
    parts = content.split(LITERAL_OPEN)
    if any(OPEN in part for part in parts):
        raise ValueError('unsupported dynamic template')
    return OPEN.join(parts)


SOURCE_FILES, TARGET_FILES = mapping('claude-codex')
LEGACY_FILES, LEGACY_TARGETS = legacy_files(), legacy_targets()
LOCATIONS = frozenset(
    [scope + '/' + p for scope in ('source', 'index', 'head') for p in set(SOURCE_FILES + LEGACY_FILES)]
    + [scope + '/' + p for scope in ('target', 'render') for p in set(TARGET_FILES + LEGACY_TARGETS)]
)



def admitted(location):
    """LOCATIONS plus the per-skill paths of any validly named skill, which no fixed list can hold."""
    if location in LOCATIONS:
        return True
    scope, _, path = location.partition('/')
    kinds = (SKILL_SOURCES + SKILL_LEGACY if scope in ('source', 'index', 'head')
             else SKILL_TARGETS if scope in ('target', 'render') else ())
    name = skill_of(path, kinds)
    try:
        return bool(name) and name in skill_names([name])
    except ValueError:
        return False


# These deployment namespaces are reserved even in a staged Claude-only profile.
# Checking their lexical relationship does not inspect inactive product files.
TARGET_REGIONS = ('.claude', '.codex', '.agents', '.config/ai-agent')

# 機器本地參數檔的封閉欄位集合。它提供路徑與身分，不提供任何寫入或發布授權。
AGENTS = ('claude', 'codex')
CONFIG_KEYS = dict(source='path', destination='path', plan_dir='path', scanner='path',
                   profile='profile', repository_profile='profile', writer='agent',
                   remote='text', branch='text', author_name='text', author_email='text',
                   auto_in='bool')


def load_config(path):
    """Machine-local sync parameters: owner-controlled, closed key set, no secrets."""
    p = Path(path)
    if not p.is_absolute() or is_redirected(p):
        raise ValueError('config path')
    info = p.stat()
    if not stat.S_ISREG(info.st_mode) or info.st_size > 65536:
        raise ValueError('config file')
    if not private_file(p, info):
        # Windows 說明是哪個主體讓它不私有（只有 SID 與權限遮罩）；POSIX 的訊息不變
        raise ValueError('config file' + (': owner=%s aces=%s user=%s token_owner=%s' % (
            *security_descriptor(p), current_user_sid(), token_owner_sid()) if WINDOWS else ''))
    doc = read_json(p)
    if type(doc) is not dict or not set(doc) <= set(CONFIG_KEYS):
        raise ValueError('config keys')
    for key, value in doc.items():
        kind = CONFIG_KEYS[key]
        if kind == 'bool':
            ok = type(value) is bool
        elif kind == 'agent':
            # writer：單一 agent、agent 清單、"any"（不檢查）或 "none"（agent 一律不可發布）。
            ok = ((type(value) is str and value in AGENTS + ('any', 'none'))
                  or (type(value) is list and 0 < len(value) <= len(AGENTS) and len(set(value)) == len(value)
                      and all(type(v) is str and v in AGENTS for v in value)))
        else:
            ok = type(value) is str and 0 < len(value) <= 4096 and not any(ord(c) < 32 for c in value)
            if ok and kind == 'path':
                ok = absolute_path(value)
            elif ok and kind == 'profile':
                ok = value in PROFILES
        if not ok:
            raise ValueError('config value')
    return doc


def overlaps(left, right):
    return left == right or left in right.parents or right in left.parents


def validate_layout(source, destination, profile, legacy=False, source_profile=None):
    """Validate roots and only managed paths; never enumerate destination.

    The managed paths are the fixed ones plus those of the source's own skills,
    found by listing three fixed source directories (source_skills).

    Explicit root aliases (including macOS /tmp) are canonicalized. Within those
    roots, symlink components, non-directory parents and hard-linked payloads
    are refused. Source may be below destination only outside target namespaces.
    """
    src, dst = Path(source).resolve(), Path(destination).resolve()
    if not src.is_dir() or not dst.is_dir() or src == dst or src in dst.parents:
        raise ValueError('invalid roots')
    # All engines allocate scratch state beneath this fixed OS temporary root.
    # A selected root must not encompass that allocation area (e.g. HOME=/tmp).
    if scratch_conflict(src, dst, temporary_root().resolve()):
        raise ValueError('root contains engine scratch area')
    if any(overlaps(src, dst / region) for region in TARGET_REGIONS):
        raise ValueError('source overlaps deployment namespace')
    skills = source_skills(src, source_profile or profile)
    if legacy:
        # 轉換前後的兩種版面都要涵蓋：v1 的 skill 在 dot_claude/skills，v2 的在共用目錄
        skills = skill_names(set(skills) | set(legacy_skills(src)))
    files, targets = mapping(profile, skills)
    if source_profile:
        files = mapping(source_profile, skills)[0]
    paths = [(src, p) for p in set(files) | (set(legacy_files(skills)) if legacy else set())]
    paths += [(dst, p) for p in targets]
    for root, relative in paths:
        rel = Path(relative)
        if rel.is_absolute() or '..' in rel.parts or str(rel) == '.':
            raise ValueError('invalid mapping')
        path = root / rel
        for part in (path, *path.parents):
            if part == root:
                break
            if is_redirected(part):
                raise ValueError('managed symlink')
            if part.exists():
                info = part.stat()
                if part != path and not stat.S_ISDIR(info.st_mode):
                    raise ValueError('invalid managed parent')
                if part == path and (not stat.S_ISREG(info.st_mode) or info.st_nlink != 1):
                    raise ValueError('invalid managed file')
    # Git reads are a separate, explicit metadata scope. Reject indirection here
    # too, so shell status cannot follow metadata links that writes would refuse.
    git_dir = src / '.git'
    if is_redirected(git_dir) or not git_dir.is_dir():
        raise ValueError('regular Git checkout required')
    def walk_error(error):
        raise error
    for parent, dirs, files in os.walk(git_dir, onerror=walk_error):
        if any(is_redirected(Path(parent) / name) for name in dirs + files):
            raise ValueError('Git metadata symlink')
    # A regular file can redirect object reads too; do not follow alternate
    # object stores or another Git directory in any entrypoint, including status.
    for name in ('commondir', 'objects/info/alternates'):
        if (git_dir / name).exists():
            raise ValueError('Git metadata indirection')
    return src, dst


class ScanError(Exception):
    pass


def require(condition):
    if not condition:
        raise ScanError()


def rules():
    data = json.loads(Path(__file__).with_name("gitleaks-rules.json").read_text())
    require(data["version"] == VERSION)
    return frozenset(data["rules"])


def read_json(path):
    require(path.is_file() and not is_redirected(path) and path.stat().st_size <= MAX_BYTES)
    # Reject duplicate JSON keys as well as malformed/truncated reports.
    def pairs(items):
        result = {}
        for key, value in items:
            require(key not in result)
            result[key] = value
        return result
    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=pairs)


def validate_report(report, code):
    require(type(report) is dict and set(report) == {"schema", "status", "findings"})
    require(type(report["schema"]) is int and report["schema"] == 1)
    expected = {0: "clean", 10: "secret", 69: "missing", 70: "error"}
    require(code in expected and report["status"] == expected[code])
    findings = report["findings"]
    require(type(findings) is list and len(findings) <= 10000)
    require(bool(findings) == (code == 10))
    allowed_rules = rules()
    for finding in findings:
        require(type(finding) is dict and set(finding) == {"file", "rule", "line"})
        require(admitted(finding["file"]) and finding["rule"] in allowed_rules)
        require(type(finding["line"]) is int and 0 < finding["line"] <= MAX_BYTES)
    return findings


def write_report(path, status, findings):
    # Caller supplies a fresh report path outside the snapshot. Never overwrite.
    with path.open("x", encoding="utf-8") as output:
        json.dump({"schema": 1, "status": status, "findings": findings}, output)
        output.write("\n")


def scan(snapshot):
    require(snapshot.is_absolute() and snapshot.is_dir() and not is_redirected(snapshot))
    binary = shutil.which("gitleaks")
    if not binary:
        return 69, []
    binary = str(Path(binary).resolve())
    with tempfile.TemporaryDirectory(prefix="ai-agent-gitleaks-", dir=str(temporary_root())) as tmp:
        make_private(tmp)
        root = Path(tmp)
        (root / "home").mkdir()
        payload = root / "payload"
        payload.mkdir()
        child_env = dict(child_environment(root / "home"), XDG_CONFIG_HOME=str(root / "home"), TMPDIR=tmp)
        version = subprocess.run([binary, "version"], cwd=tmp, env=child_env,
                                 capture_output=True, timeout=10)
        require(version.returncode == 0 and not version.stderr)
        require(version.stdout.strip() == VERSION.encode("ascii"))
        mapping = {}
        for parent, dirs, files in os.walk(snapshot, followlinks=False, onerror=lambda _: require(False)):
            for name in dirs:
                require(not is_redirected(Path(parent) / name))
            for name in sorted(files):
                original = Path(parent) / name
                location = original.relative_to(snapshot).as_posix()
                require(admitted(location))
                mode = original.lstat().st_mode
                require(stat.S_ISREG(mode) and mode & 0o444)
                require(original.stat().st_size <= MAX_BYTES)
                with original.open("rb") as input_file:
                    content = input_file.read(MAX_BYTES + 1)
                require(len(content) <= MAX_BYTES and b"\x00" not in content)
                content.decode("utf-8", errors="strict")
                # Neutral filenames avoid Gitleaks' default path allowlists and
                # prevent input-controlled paths/config/ignore files affecting it.
                safe_name = "%04d.txt" % len(mapping)
                (payload / safe_name).write_bytes(content)
                mapping[safe_name] = location
        require(mapping)
        config = root / "gitleaks.toml"
        config.write_text("[extend]\nuseDefault = true\n", encoding="utf-8")
        ignore = root / "empty.ignore"
        ignore.write_text("", encoding="utf-8")
        raw_report = root / "report.json"
        result = subprocess.run([
            binary, "dir", str(payload), "--config", str(config),
            "--gitleaks-ignore-path", str(ignore), "--ignore-gitleaks-allow",
            "--exit-code", "10", "--redact=100", "--no-banner", "--no-color",
            "--log-level", "error", "--report-format", "json", "--report-path", str(raw_report),
            "--max-target-megabytes", "0", "--max-decode-depth", "5",
            "--max-archive-depth", "0", "--timeout", "90",
        ], cwd=tmp, env=child_env, capture_output=True, timeout=100)
        require(result.returncode in (0, 10) and not result.stdout and not result.stderr)
        raw = read_json(raw_report)
        require(type(raw) is list and bool(raw) == (result.returncode == 10))
        require(len(raw) <= 10000)
        known_rules = rules()
        findings = set()
        for item in raw:
            require(type(item) is dict)
            rule = item["RuleID"]
            require(rule in known_rules)
            file = Path(item["File"])
            if not file.is_absolute():
                file = root / file
            require(file.parent == payload and file.name in mapping)
            line = item["StartLine"]
            require(type(line) is int and 0 < line <= MAX_BYTES)
            # Never copy Match, Secret, Description, Fingerprint, Commit, etc.
            findings.add((mapping[file.name], rule, line))
        return result.returncode, [dict(file=f, rule=r, line=l) for f, r, l in sorted(findings)]


def main():
    os.umask(0o077)
    if len(sys.argv) in (5, 6) and sys.argv[1] == '--validate-layout':
        try:
            validate_layout(sys.argv[2], sys.argv[3], sys.argv[4], source_profile=sys.argv[5] if len(sys.argv) == 6 else None)
        except (ValueError, OSError):
            return 65
        return 0
    if len(sys.argv) == 4 and sys.argv[1] == '--config':
        # 供 shell 入口讀取單一欄位；無此欄位輸出空字串，無效檔案回傳 78。
        try:
            doc = load_config(sys.argv[2])
        except (ValueError, OSError, ScanError):
            return 78
        value = doc.get(sys.argv[3])
        if value is not None:
            print('true' if value is True else 'false' if value is False else ','.join(value) if type(value) is list else value)
        return 0
    if len(sys.argv) in (4, 5) and sys.argv[1] in ('--schema', '--retired'):
        # 給了 source 根目錄就用它自己的 skill 集合。--retired 從 stdin 讀 HEAD 的路徑，
        # 只列出 HEAD 有、工作目錄已經沒有的 skill 的路徑。
        require(sys.argv[3] in ('source', 'target'))
        try:
            skills = source_skills(sys.argv[4], sys.argv[2]) if len(sys.argv) == 5 else SKILLS
            if sys.argv[1] == '--retired':
                require(len(sys.argv) == 5)
                head = skills_in(sys.stdin.read().splitlines(), sys.argv[2])
                skills = tuple(s for s in head if s not in skills)
            paths = mapping(sys.argv[2], skills)[sys.argv[3] == 'target']
        except (ValueError, OSError):
            return 65
        if sys.argv[1] == '--retired':
            paths = [p for p in paths if skill_of(p)]
        if paths:
            print('\n'.join(paths))
        return 0
    if len(sys.argv) == 3 and sys.argv[1] == '--make-private':
        # 上線用：把參數檔或 plan_dir 設成只有自己能存取（#15 W5）；路徑要存在、絕對、不是重導向
        target = Path(sys.argv[2])
        require(target.is_absolute() and not is_redirected(target) and target.exists())
        try:
            protect(target)
        except OSError:
            print('FAIL: ' + str(target) + ' could not be made private; check its owner and ACL')
            return 70
        print('OK: ' + str(target) + ' is private')
        return 0
    if len(sys.argv) == 3 and sys.argv[1] == '--validate-shared':
        decode_shared(Path(sys.argv[2]).read_bytes())
        return 0
    if len(sys.argv) == 3 and sys.argv[1] == '--wrapper':
        sys.stdout.buffer.write(wrapper(sys.argv[2]))
        return 0
    if len(sys.argv) == 4 and sys.argv[1] == "--display-report":
        # Validate the entire document before emitting even the first finding.
        findings = validate_report(read_json(Path(sys.argv[2])), int(sys.argv[3]))
        for item in findings:
            print("FINDING: %s:%d rule=%s" % (item["file"], item["line"], item["rule"]))
        return 0
    require(len(sys.argv) == 3)
    snapshot, output = map(Path, sys.argv[1:])
    require(output.is_absolute() and not output.exists() and not is_redirected(output))
    require(snapshot.resolve() not in output.resolve().parents)
    try:
        code, findings = scan(snapshot)
    except (OSError, ValueError, KeyError, TypeError, RecursionError, ScanError, subprocess.SubprocessError):
        code, findings = 70, []
    write_report(output, {0: "clean", 10: "secret", 69: "missing", 70: "error"}[code], findings)
    return code


if __name__ == "__main__":
    def interrupted(_signum, _frame):
        # Unwind subprocess.run/TemporaryDirectory on normal termination.
        # SIGKILL cannot be handled; snapshots have owner-only permissions.
        raise KeyboardInterrupt()
    # SIGHUP 在部分平台（例如原生 Windows 的 Python）不存在；缺少時只處理 SIGTERM
    for sig in (signal.SIGTERM, getattr(signal, 'SIGHUP', None)):
        if sig is not None:
            signal.signal(sig, interrupted)
    try:
        sys.exit(main())
    except (OSError, ValueError, KeyError, TypeError, RecursionError, ScanError, subprocess.SubprocessError, KeyboardInterrupt):
        # Exception messages may contain user bytes: never print them or tracebacks.
        sys.exit(70)
