#!/usr/bin/env python3
"""Offline Gitleaks adapter and strict redacted-report renderer (stdlib only)."""
import json
import os
from pathlib import Path
import shutil
import signal
import stat
import subprocess
import sys
import tempfile

VERSION = "8.30.1"
MAX_BYTES = 8 * 1024 * 1024
SKILLS = ('dotfiles-sync', 'd3-component', 'deploy', 'excel-import', 'review', 'supabase-migrate')
PROFILES = ('claude', 'codex', 'claude-codex')
PREFIX = '.chezmoitemplates/ai/'
SCRIPTS = ('sync.sh', 'scan-secrets.py', 'sync-write.py', 'sync-migrate.py', 'gitleaks-rules.json')
BANNER = b'<!-- Generated by chezmoi. Edit .chezmoitemplates/ai/ in the source. -->\n'


def mapping(profile):
    if profile not in PROFILES:
        raise ValueError('invalid profile')
    products = ('claude', 'codex') if profile == 'claude-codex' else (profile,)
    sources = [PREFIX + 'shared/instructions.md']
    sources += [PREFIX + 'shared/skills/' + s + '/SKILL.md' for s in SKILLS]
    sources += [PREFIX + 'shared/scripts/' + s for s in SCRIPTS]
    if 'claude' in products:
        sources += [PREFIX + 'shared/scripts/legacy-sync.sh']
    sources += [PREFIX + 'adapters/' + p + '.md' for p in products]
    targets = []
    for product in products:
        sources.append('dot_' + product + ('/CLAUDE.md.tmpl' if product == 'claude' else '/AGENTS.md.tmpl'))
        targets.append('.' + product + ('/CLAUDE.md' if product == 'claude' else '/AGENTS.md'))
        skill_home = 'claude' if product == 'claude' else 'agents'
        for skill in SKILLS:
            sources.append('dot_' + skill_home + '/skills/' + skill + '/SKILL.md.tmpl')
            targets.append('.' + skill_home + '/skills/' + skill + '/SKILL.md')
    for name in SCRIPTS:
        sources.append('dot_config/ai-agent/bin/' + ('' if name.endswith('.json') else 'executable_') + name + '.tmpl')
        targets.append('.config/ai-agent/bin/' + name)
    if 'claude' in products:
        sources += ['dot_claude/skills/dotfiles-sync/executable_sync.sh.tmpl', 'dot_claude/settings.json']
        targets += ['.claude/skills/dotfiles-sync/sync.sh', '.claude/settings.json']
    sources += ['.chezmoiignore', '.gitignore', '.gitattributes']
    return tuple(sources), tuple(targets)


def wrapper(path):
    opening, closing = '{' * 2, '}' * 2
    def include(p, trim=True):
        name = p[len('.chezmoitemplates/'):]
        return (opening + ' template "' + name + '" . ' + ('-' if trim else '') + closing + '\n').encode()
    if path in ('dot_claude/CLAUDE.md.tmpl', 'dot_codex/AGENTS.md.tmpl'):
        product = 'claude' if path.startswith('dot_claude/') else 'codex'
        return BANNER + include(PREFIX + 'shared/instructions.md', False) + include(PREFIX + 'adapters/' + product + '.md')
    for skill in SKILLS:
        if path in ('dot_claude/skills/' + skill + '/SKILL.md.tmpl', 'dot_agents/skills/' + skill + '/SKILL.md.tmpl'):
            return include(PREFIX + 'shared/skills/' + skill + '/SKILL.md')
    if path == 'dot_claude/skills/dotfiles-sync/executable_sync.sh.tmpl':
        return include(PREFIX + 'shared/scripts/legacy-sync.sh')
    for script in SCRIPTS:
        if path == 'dot_config/ai-agent/bin/' + ('' if script.endswith('.json') else 'executable_') + script + '.tmpl':
            return include(PREFIX + 'shared/scripts/' + script)
    raise ValueError('unknown wrapper')


OPEN = b'{' * 2
LITERAL_OPEN = OPEN + b' "' + OPEN + b'" ' + b'}' * 2


def encode_shared(content):
    """Represent arbitrary literal UTF-8 text using only a static opener escape."""
    return content.replace(OPEN, LITERAL_OPEN)


def decode_shared(content):
    parts = content.split(LITERAL_OPEN)
    if any(OPEN in part for part in parts):
        raise ValueError('unsupported dynamic template')
    return OPEN.join(parts)


SOURCE_FILES, TARGET_FILES = mapping('claude-codex')
LEGACY_FILES = ('dot_claude/CLAUDE.md', 'dot_claude/settings.json',
                'dot_claude/skills/dotfiles-sync/executable_sync.sh', '.chezmoiignore', '.gitignore', '.gitattributes') + tuple(
                    'dot_claude/skills/' + s + '/SKILL.md' for s in SKILLS)
LEGACY_TARGETS = ('.claude/CLAUDE.md', '.claude/settings.json', '.claude/skills/dotfiles-sync/sync.sh') + tuple(
    '.claude/skills/' + s + '/SKILL.md' for s in SKILLS)
LOCATIONS = frozenset(
    [scope + '/' + p for scope in ('source', 'index', 'head') for p in set(SOURCE_FILES + LEGACY_FILES)]
    + [scope + '/' + p for scope in ('target', 'render') for p in set(TARGET_FILES + LEGACY_TARGETS)]
)

# These deployment namespaces are reserved even in a staged Claude-only profile.
# Checking their lexical relationship does not inspect inactive product files.
TARGET_REGIONS = ('.claude', '.codex', '.agents', '.config/ai-agent')

# 機器本地參數檔的封閉欄位集合。它提供路徑與身分，不提供任何寫入或發布授權。
CONFIG_KEYS = dict(source='path', destination='path', plan_dir='path', scanner='path',
                   profile='profile', repository_profile='profile', writer='agent',
                   remote='text', branch='text', author_name='text', author_email='text',
                   auto_in='bool')


def load_config(path):
    """Machine-local sync parameters: owner-controlled, closed key set, no secrets."""
    p = Path(path)
    if not p.is_absolute() or p.is_symlink():
        raise ValueError('config path')
    info = p.stat()
    if (not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid()
            or info.st_mode & 0o022 or info.st_size > 65536):
        raise ValueError('config file')
    doc = read_json(p)
    if type(doc) is not dict or not set(doc) <= set(CONFIG_KEYS):
        raise ValueError('config keys')
    for key, value in doc.items():
        kind = CONFIG_KEYS[key]
        if kind == 'bool':
            ok = type(value) is bool
        else:
            ok = type(value) is str and 0 < len(value) <= 4096 and not any(ord(c) < 32 for c in value)
            if ok and kind == 'path':
                ok = value.startswith('/')
            elif ok and kind == 'profile':
                ok = value in PROFILES
            elif ok and kind == 'agent':
                ok = value in ('claude', 'codex')
        if not ok:
            raise ValueError('config value')
    return doc


def overlaps(left, right):
    return left == right or left in right.parents or right in left.parents


def validate_layout(source, destination, profile, legacy=False, source_profile=None):
    """Validate roots and only fixed managed paths; never enumerate destination.

    Explicit root aliases (including macOS /tmp) are canonicalized. Within those
    roots, symlink components, non-directory parents and hard-linked payloads
    are refused. Source may be below destination only outside target namespaces.
    """
    src, dst = Path(source).resolve(), Path(destination).resolve()
    if not src.is_dir() or not dst.is_dir() or src == dst or src in dst.parents:
        raise ValueError('invalid roots')
    # All engines allocate scratch state beneath this fixed OS temporary root.
    # A selected root must not encompass that allocation area (e.g. HOME=/tmp).
    temporary_parent = Path('/tmp').resolve()
    if any(root == temporary_parent or root in temporary_parent.parents for root in (src, dst)):
        raise ValueError('root contains engine scratch area')
    if any(overlaps(src, dst / region) for region in TARGET_REGIONS):
        raise ValueError('source overlaps deployment namespace')
    files, targets = mapping(profile)
    if source_profile:
        files = mapping(source_profile)[0]
    paths = [(src, p) for p in set(files) | (set(LEGACY_FILES) if legacy else set())]
    paths += [(dst, p) for p in targets]
    for root, relative in paths:
        rel = Path(relative)
        if rel.is_absolute() or '..' in rel.parts or str(rel) == '.':
            raise ValueError('invalid mapping')
        path = root / rel
        for part in (path, *path.parents):
            if part == root:
                break
            if part.is_symlink():
                raise ValueError('managed symlink')
            if part.exists():
                info = part.stat()
                if part != path and not stat.S_ISDIR(info.st_mode):
                    raise ValueError('invalid managed parent')
                if part == path and (not stat.S_ISREG(info.st_mode) or info.st_nlink != 1):
                    raise ValueError('invalid managed file')
    # Git reads are a separate, explicit metadata scope. Reject indirection here
    # too, so shell status cannot follow metadata links that writes would refuse.
    git_dir = src / '.git'
    if git_dir.is_symlink() or not git_dir.is_dir():
        raise ValueError('regular Git checkout required')
    def walk_error(error):
        raise error
    for parent, dirs, files in os.walk(git_dir, onerror=walk_error):
        if any((Path(parent) / name).is_symlink() for name in dirs + files):
            raise ValueError('Git metadata symlink')
    # A regular file can redirect object reads too; do not follow alternate
    # object stores or another Git directory in any entrypoint, including status.
    for name in ('commondir', 'objects/info/alternates'):
        if (git_dir / name).exists():
            raise ValueError('Git metadata indirection')
    return src, dst


class ScanError(Exception):
    pass


def require(condition):
    if not condition:
        raise ScanError()


def rules():
    data = json.loads(Path(__file__).with_name("gitleaks-rules.json").read_text())
    require(data["version"] == VERSION)
    return frozenset(data["rules"])


def read_json(path):
    require(path.is_file() and not path.is_symlink() and path.stat().st_size <= MAX_BYTES)
    # Reject duplicate JSON keys as well as malformed/truncated reports.
    def pairs(items):
        result = {}
        for key, value in items:
            require(key not in result)
            result[key] = value
        return result
    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=pairs)


def validate_report(report, code):
    require(type(report) is dict and set(report) == {"schema", "status", "findings"})
    require(type(report["schema"]) is int and report["schema"] == 1)
    expected = {0: "clean", 10: "secret", 69: "missing", 70: "error"}
    require(code in expected and report["status"] == expected[code])
    findings = report["findings"]
    require(type(findings) is list and len(findings) <= 10000)
    require(bool(findings) == (code == 10))
    allowed_rules = rules()
    for finding in findings:
        require(type(finding) is dict and set(finding) == {"file", "rule", "line"})
        require(finding["file"] in LOCATIONS and finding["rule"] in allowed_rules)
        require(type(finding["line"]) is int and 0 < finding["line"] <= MAX_BYTES)
    return findings


def write_report(path, status, findings):
    # Caller supplies a fresh report path outside the snapshot. Never overwrite.
    with path.open("x", encoding="utf-8") as output:
        json.dump({"schema": 1, "status": status, "findings": findings}, output)
        output.write("\n")


def scan(snapshot):
    require(snapshot.is_absolute() and snapshot.is_dir() and not snapshot.is_symlink())
    binary = shutil.which("gitleaks")
    if not binary:
        return 69, []
    binary = str(Path(binary).resolve())
    with tempfile.TemporaryDirectory(prefix="ai-agent-gitleaks-", dir="/tmp") as tmp:
        root = Path(tmp)
        (root / "home").mkdir()
        payload = root / "payload"
        payload.mkdir()
        child_env = {"HOME": str(root / "home"), "LC_ALL": "C", "PATH": os.defpath,
                     "XDG_CONFIG_HOME": str(root / "home"), "TMPDIR": tmp}
        version = subprocess.run([binary, "version"], cwd=tmp, env=child_env,
                                 capture_output=True, timeout=10)
        require(version.returncode == 0 and not version.stderr)
        require(version.stdout.strip() == VERSION.encode("ascii"))
        mapping = {}
        for parent, dirs, files in os.walk(snapshot, followlinks=False, onerror=lambda _: require(False)):
            for name in dirs:
                require(not (Path(parent) / name).is_symlink())
            for name in sorted(files):
                original = Path(parent) / name
                location = original.relative_to(snapshot).as_posix()
                require(location in LOCATIONS)
                mode = original.lstat().st_mode
                require(stat.S_ISREG(mode) and mode & 0o444)
                require(original.stat().st_size <= MAX_BYTES)
                with original.open("rb") as input_file:
                    content = input_file.read(MAX_BYTES + 1)
                require(len(content) <= MAX_BYTES and b"\x00" not in content)
                content.decode("utf-8", errors="strict")
                # Neutral filenames avoid Gitleaks' default path allowlists and
                # prevent input-controlled paths/config/ignore files affecting it.
                safe_name = "%04d.txt" % len(mapping)
                (payload / safe_name).write_bytes(content)
                mapping[safe_name] = location
        require(mapping)
        config = root / "gitleaks.toml"
        config.write_text("[extend]\nuseDefault = true\n", encoding="utf-8")
        ignore = root / "empty.ignore"
        ignore.write_text("", encoding="utf-8")
        raw_report = root / "report.json"
        result = subprocess.run([
            binary, "dir", str(payload), "--config", str(config),
            "--gitleaks-ignore-path", str(ignore), "--ignore-gitleaks-allow",
            "--exit-code", "10", "--redact=100", "--no-banner", "--no-color",
            "--log-level", "error", "--report-format", "json", "--report-path", str(raw_report),
            "--max-target-megabytes", "0", "--max-decode-depth", "5",
            "--max-archive-depth", "0", "--timeout", "90",
        ], cwd=tmp, env=child_env, capture_output=True, timeout=100)
        require(result.returncode in (0, 10) and not result.stdout and not result.stderr)
        raw = read_json(raw_report)
        require(type(raw) is list and bool(raw) == (result.returncode == 10))
        require(len(raw) <= 10000)
        known_rules = rules()
        findings = set()
        for item in raw:
            require(type(item) is dict)
            rule = item["RuleID"]
            require(rule in known_rules)
            file = Path(item["File"])
            if not file.is_absolute():
                file = root / file
            require(file.parent == payload and file.name in mapping)
            line = item["StartLine"]
            require(type(line) is int and 0 < line <= MAX_BYTES)
            # Never copy Match, Secret, Description, Fingerprint, Commit, etc.
            findings.add((mapping[file.name], rule, line))
        return result.returncode, [dict(file=f, rule=r, line=l) for f, r, l in sorted(findings)]


def main():
    os.umask(0o077)
    if len(sys.argv) in (5, 6) and sys.argv[1] == '--validate-layout':
        try:
            validate_layout(sys.argv[2], sys.argv[3], sys.argv[4], source_profile=sys.argv[5] if len(sys.argv) == 6 else None)
        except (ValueError, OSError):
            return 65
        return 0
    if len(sys.argv) == 4 and sys.argv[1] == '--config':
        # 供 shell 入口讀取單一欄位；無此欄位輸出空字串，無效檔案回傳 78。
        try:
            doc = load_config(sys.argv[2])
        except (ValueError, OSError, ScanError):
            return 78
        value = doc.get(sys.argv[3])
        if value is not None:
            print('true' if value is True else 'false' if value is False else value)
        return 0
    if len(sys.argv) == 4 and sys.argv[1] == '--schema':
        files, targets = mapping(sys.argv[2])
        require(sys.argv[3] in ('source', 'target'))
        print('\n'.join(files if sys.argv[3] == 'source' else targets))
        return 0
    if len(sys.argv) == 3 and sys.argv[1] == '--validate-shared':
        decode_shared(Path(sys.argv[2]).read_bytes())
        return 0
    if len(sys.argv) == 3 and sys.argv[1] == '--wrapper':
        sys.stdout.buffer.write(wrapper(sys.argv[2]))
        return 0
    if len(sys.argv) == 4 and sys.argv[1] == "--display-report":
        # Validate the entire document before emitting even the first finding.
        findings = validate_report(read_json(Path(sys.argv[2])), int(sys.argv[3]))
        for item in findings:
            print("FINDING: %s:%d rule=%s" % (item["file"], item["line"], item["rule"]))
        return 0
    require(len(sys.argv) == 3)
    snapshot, output = map(Path, sys.argv[1:])
    require(output.is_absolute() and not output.exists() and not output.is_symlink())
    require(snapshot.resolve() not in output.resolve().parents)
    try:
        code, findings = scan(snapshot)
    except (OSError, ValueError, KeyError, TypeError, RecursionError, ScanError, subprocess.SubprocessError):
        code, findings = 70, []
    write_report(output, {0: "clean", 10: "secret", 69: "missing", 70: "error"}[code], findings)
    return code


if __name__ == "__main__":
    def interrupted(_signum, _frame):
        # Unwind subprocess.run/TemporaryDirectory on normal termination.
        # SIGKILL cannot be handled; snapshots have owner-only permissions.
        raise KeyboardInterrupt()
    for sig in (signal.SIGTERM, signal.SIGHUP):
        signal.signal(sig, interrupted)
    try:
        sys.exit(main())
    except (OSError, ValueError, KeyError, TypeError, RecursionError, ScanError, subprocess.SubprocessError, KeyboardInterrupt):
        # Exception messages may contain user bytes: never print them or tracebacks.
        sys.exit(70)
